model_list:
  - model_name: deepseek-r1
    litellm_params:
      model: openrouter/deepseek/deepseek-r1-0528:free
      api_base: https://openrouter.ai/api/v1
      api_key: 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

litellm_settings:
  drop_params: true
  set_verbose: true